- README.md
Why?
View the [rich changes ](https://github.com/BenEmdon/FunctionalTableData/blob/ba27437f11898f58f08574be4cecb75743d33cd3/README.md)
> Gave code block comment a break in README

- FunctionalTableData/CellActions.swift
`CellActions` has two initializers. The second one wasn't propagating the `canSelectAction` argument to the first one.
> fix bug where canSelectAction wasn't being passed through the initializer chain

- FunctionalTableData/TableSectionChangeSet.swift
The exception handlers sometimes check these properties, allow them to be used outside of the module
> Allow these to be read outside the module

- FunctionalTableData/CollectionView/FunctionalCollectionData.swift
- FunctionalTableData/TableView/FunctionalTableData.swift
This PR adds methods to FTD and FCD for getting the `KeyPath` at a specific location within the table/collection view. These are analogous to `UITableView.indexPathForRow(at:)` and `UICollectionView.indexPathForItem(at:)`.
> Add hit-testing methods

- FunctionalTableData/CollectionView/FunctionalCollectionData.swift
- FunctionalTableData/TableView/FunctionalTableData.swift
I was making a test app and one of the UIScrollViewDelegate functions I needed wasn't propagated by FunctionalTableData, so I added it and added the other missing functions to to FunctionalTableData and FunctionalCollectionData while I was at it.
> add support for missing UIScrollViewDelegate functions

- FunctionalTableData/TableView/FunctionalTableData.swift
In some situations operations can pile up in the renderAndDiff queue. It's not necessary to run all of them because the last one added should provide the correct state to display. This PR cancels any outstanding operations that are not already executing before adding the new operation to the queue.
> Cancel outstanding operations

- FunctionalTableData/FunctionalTableData.h
Added void to Block definition because we don’t expect params to be passed. This is to fix an issue on an internal project where tests were not building.
> Added void to catchAndRethrowException block definition 

- CHANGELOG.md
- FunctionalTableData/CollectionView/FunctionalCollectionData.swift
- FunctionalTableData/TableView/FunctionalTableData.swift
- FunctionalTableDataTests/FunctionalDataTests.swift
The function was never made public, so was unavailable outside of the module, and hasn't been touched since the project released.
After discussion, this function goes against the mantra of the FunctionalTable/CollectionData model as a single row isn't meant to be touched. As @g-Off also pointed out, there's no guarantees the `CellConfigType` matches what's in the row being changed, and there's no checks to see if it might be interrupting an active `renderAndDiff`
> Remove unused updateRow function

- FunctionalTableData/CollectionView/FunctionalCollectionData.swift
`FunctionalTableData` had this function and it was missing in `FunctionalCollectionData`.
> Previewing Context for FCD

- FunctionalTableDataDemo/Base.lproj/Main.storyboard
Removed the warnings by removing the cells from the storyboards. The library is creating them anyway
> Remove the dynamic cells

- FunctionalTableData.xcodeproj/project.pbxproj
- FunctionalTableDataTests/TableSectionStyleTests.swift
This adds `key` and `style` to the equality definition of `CellConfigType`. While most style changes are accompanied by state changes, it's not always the case for indexed items that change positions. Adding style makes it more likely we update cells when they change their merged style. This also allows us to compare `CellConfigType`s more accurately outside of FunctionalTableData.
- Allow demo app to be used with iOS 9.0+
- 🔥 1 warning
> Host cell equality

- FunctionalTableData/CellActions.swift
- FunctionalTableData/CollectionView/FunctionalCollectionData.swift
- FunctionalTableData/TableView/FunctionalTableData.swift
- FunctionalTableDataDemo/CollectionExampleController.swift
- FunctionalTableDataDemo/TableExampleController.swift
Been using this framework in a project for a bit and so far it's been great, but a few things are missing that I would like to fix. Examples of changes are included in the demo app.
If this closure exists, `allowsMultipleSelection` is broken. `willSelectRowAt` now checks for `allowsMultipleSelection` and doesn't deselect the currently selected row if it's enabled. `CollectionData` is also fixed for `allowsMultipleSelection`, although it does not currently call `canSelectAction` at all. Not sure if that's intended or an oversight?
The current behaviour only calls this on `didSelect`. It's useful to know when the user deselects as well, so the closure now sends a boolean indicating whether the user is selecting or deselecting.
> Improve canSelectAction, selectionAction

- .travis.yml
Travis' YAML file configuration implies that tests run automatically, they don't. This kicks off the test phase using a script because even if you can get the config right it uses `xctool` by default.
How to validate:
If you look at previous test runs there is no build output and they all "succeed" in about 15s. This PR's CI output shows a build and test output and takes ~1.5mins
> tests aren't running on travis, using the script option kicks them off

- FunctionalTableData/HostCell.swift
HostCell isEqual has been causing crashes since Swift 4.1. We don't have a reproducible test case for this, but we have similar crashes caused by the optimizer. As a work around we can tell the isEqual function to never inline and cross our fingers that this crash stops happening.
Example of top of stack from a crash report:
```swift
0  Shopify                 __hidden#21025_ (__hidden#20994_:107:14)
1  Shopify                 isEqual (HostCell.swift:97:24)
2  Shopify                 isRow (TableSectionChangeSet.swift:164:16)
3  Shopify                 isRow (TableSectionChangeSet.swift)
4  Shopify                 calculateChanges (TableSectionChangeSet.swift:137:7)
5  Shopify                 init (TableSectionChangeSet.swift:76:3)
6  Shopify                 calculateTableChanges …
```
> Prevent inlining of HostCell.isEqual

- FunctionalTableData/CollectionView/FunctionalCollectionData.swift
- FunctionalTableData/TableView/FunctionalTableData.swift
This PR adds an optional callback for `UIAccessibilityScrollViewDelegate.accessibilityScrollStatus`, which can be used to report the current scroll position of the table in an accessible way: e.g. "Page 2 of 3" (for general screen content), "Aardvark to Marmoset" (for alphabetised lists), "15th January to 23rd March" (for chronological lists) etc. This is a useful navigational aid for VoiceOver users.
This PR also adds a helper method to get all currently-visible cells, which proved useful for constructing these accessibility descriptions.
> Add hooks for reporting accessibility scroll status

- FunctionalTableData/CollectionView/FunctionalCollectionData.swift
- FunctionalTableData/TableView/FunctionalTableData.swift
Oops. In https://github.com/Shopify/FunctionalTableData/pull/100 I forgot to make `FunctionalTableData` and `FunctionalCollectionData` actually advertise that they conform to `UIScrollViewAccessibilityDelegate`, which meant `accessibilityScrollStatus` was never called. This PR fixes that.
> Make FTD and FCD conform to UIScrollViewAccessibilityDelegate

- FunctionalTableData/Extensions/Array+TableSection.swift
Fixes a crash that would happen when a crash happened. Attempting to serialize a Set using JSONSerialization doesn't work, it needs to be an Array
> JSONSerialization doesn't support Set's, so return an Array

- FunctionalTableData/HostCell.swift
- FunctionalTableData/TableSectionChangeSet.swift
Changing `TableSectionChangeSet` from a struct to class.
Since Swift 4.1 we have seen many crashes in `HostCell.isEqual`. None of the crashes make sense, but the crash is a SEGV_ACCERR which implies that multiple threads are accessing the same memory. 
Changing the change set from struct to class and eliminating the mutating functions *_maybe_* makes these crashes go away.
> Change changeset to class

- FunctionalTableDataTests/TableSectionsValidationTests.swift
This PR fixes a conditional cast from `[String]` to `Set<String>` that now (as of Swift 4.2 maybe?) always fails, which was causing a pair of tests to fail.
> Fix failing typecast in section validation tests

- FunctionalTableData.xcodeproj/project.pbxproj
- FunctionalTableData/CollectionView/FunctionalCollectionData.swift
- FunctionalTableData/TableSection.swift
- FunctionalTableData/TableView/FunctionalTableData.swift
- FunctionalTableDataTests/TableCellReuseTests.swift
Whenever a cell gets updated, `FunctionalXData` calculates the "merged" style for that cell (the combination of the cell's style and its section's style) and then asks that style to apply itself to the cell view using `CellStyle.configure(cell:)`
However:
`CellConfigType.style` and `TableSection.style` are optionals that default to `nil`, and when they're both `nil` then `TableSection.mergedStyle(for: cell)` also returns `nil`. **In this case, we don't apply *any* style to the cell and it retains its previous appearance.** This caused previous styles to be 'leaked': e.g. background colors, accessory types etc. could be left over from a previous style.
It also meant that certain default layout properties we assumed were always configured (e.g. `layoutMargins` and …
> Apply default CellStyle when no custom style is provided

- FunctionalTableData/TableView/FunctionalTableData.swift
- FunctionalTableDataTests/FunctionalDataTests.swift
Adds an accessibility identifier to each cell so we can access them more easily for UI Testing. Since we already add unique keys to each section configuration and cell configuration, we should be able to reuse them as the accessibility identifiers. This way we don't have to input any extra identifiers.
If you have two components inside a cell you want to access separately you can set those components as accessibility elements to override the cell's accessibility identifier.
Since accessibility identifiers are only used for UITesting, this shouldn't affect any integrations with Voice Over.
Similar to the test, if we had a section:
```swift
TableSection(key: "sectionKey", rows: [SomeCell(key: "cellKey")])
```
The `accessibilityIdentifier` of the cell inside that section will be …
> Set cell accessibility identifiers to section+cell keys

- FunctionalTableData/CellStyle.swift
- FunctionalTableDataTests/CellStyleTests.swift
Previously, `CellStyle` would force a cell's background color to white if no specific background color was provided. This is an assumption that a public framework shouldn't be making, and it prevents you from defining cells with no background color at all.
This PR:
- moves the default color to a static `CellStyle` property that can be overridden by client apps (including setting it to `nil`.)
- allows cells to have no background color.
- avoids creating a background view on every cell update just to hold the color.
- makes the background color (if any) stack with the background view (if any).
> Remove hardcoded white background color from CellStyle

- FunctionalTableData/CollectionView/FunctionalCollectionData.swift
- FunctionalTableData/TableView/FunctionalTableData.swift
Resolves https://github.com/Shopify/FunctionalTableData/issues/113
The `tableView.frame` was directly accessed in the `BlockOperation`. As suggested by the main thread checker, this should only be accessed in the main thread.
> Fixed background thread access UI component

- FunctionalTableData.xcodeproj/project.pbxproj
- FunctionalTableData/BackgroundViewProvider.swift
- FunctionalTableData/CellStyle.swift
- FunctionalTableDataTests/CellStyleTests.swift
Re-opening this as changes have been pushed to the old branch since `stalebot` killed the PR.
The `backgroundView` property on `CellStyle` is expensive - background views are created on every render pass, even though they are rarely used. 
The `BackgroundViewProvider` allows `CellStyle` to request an optional background view when its being dequeued; the only time it's actually needed. 
Fixes https://github.com/Shopify/FunctionalTableData/issues/105
> Deprecate backgroundView for backgroundViewProvider

- FunctionalTableData/TableSectionChangeSet.swift
- FunctionalTableData/TableSectionHeaderFooter.swift
- FunctionalTableDataTests/TableSectionChangeSetTests.swift
**Problem**
The state of a `TableSection`s header/footer is not considered in the tableView diff. This means that changes to a header or footer's state will not cause its `TableSection` to be reloaded during a `renderAndDiff`.
**Solution**
Add `isEqual(...) -> Bool` to the `TableHeaderFooterConfigType` protocol. This allows our conforming types to define what equality means. There is also an extension with a default implementation so that these changes are not breaking - simply check to make sure the types match.
A header/footers updater is only called when a header/footer is dequeued. The only way to ensure a header/footer is dequeued is to reload the table section it belongs to. So, when building the change set:
1. If the section has been deleted, inserted, or moved, this case is …
> Include section header state changes in sections diff

- FunctionalTableData.xcodeproj/project.pbxproj
- FunctionalTableData/CollectionView/FunctionalCollectionData.swift
- FunctionalTableData/ScrollViewDelegate.swift
- FunctionalTableData/TableView/FunctionalTableData.swift
This is for use instead of the closure based mechanism
Uses NSObject's forwardingTarget to send UIScrollViewDelegate based messages to a separate object and removes the need for Functional(Table|Collection)Data to implement and forward all of the various UIScrollViewDelegate based messages itself. Backwards compatibility is maintained with a separate internal object that maintains the closures and will call them (so long as a delegate implementing the same method doesn't exist). In future we can remove this backwards compatible support and rely solely on the UIScrollViewDelegate.
> Adds support for setting a UIScrollViewDelegate

- FunctionalTableData.xcodeproj/project.pbxproj
- FunctionalTableData/CollectionView/FunctionalCollectionData+UICollectionViewDataSource.swift
- FunctionalTableData/CollectionView/FunctionalCollectionData+UICollectionViewDelegate.swift
- FunctionalTableData/CollectionView/FunctionalCollectionData.swift
- FunctionalTableData/ScrollViewDelegate.swift
- FunctionalTableData/TableView/FunctionalTableData+UITableViewDataSource.swift
- FunctionalTableData/TableView/FunctionalTableData+UITableViewDelegate.swift
- FunctionalTableData/TableView/FunctionalTableData.swift
Separates the UICollectionView and UITableView Delegate/DataSource objects into their own objects. This removes the need for FunctionalTableData to extend NSObject, isolates the logic/code associated with the protocols.
> Moves the datasource/delegate into own files

- FunctionalTableData.xcodeproj/project.pbxproj
- FunctionalTableData/CollectionView/FunctionalCollectionData.swift
- FunctionalTableData/HostCell.swift
- FunctionalTableData/ItemPath.swift
- FunctionalTableData/TableSection.swift
- FunctionalTableData/TableView/FunctionalTableData+UITableViewDataSource.swift
- FunctionalTableData/TableView/FunctionalTableData+UITableViewDelegate.swift
- FunctionalTableData/TableView/FunctionalTableData.swift
KeyPath is a built in Swift type, and having two different KeyPath (FunctionalTableData.KeyPath and FunctionalCollectionData.KeyPath) isn't necessary, so adding the ItemPath type that will be used by both
> adding the ItemPath type to replace KeyPath

- FunctionalTableData.xcodeproj/project.pbxproj
- FunctionalTableData/CellActions.swift
- FunctionalTableData/TableView/FunctionalTableData+UITableViewDataSource.swift
- FunctionalTableData/TableView/FunctionalTableData+UITableViewDelegate.swift
- FunctionalTableDataTests/FunctionalTableDataDelegateTests.swift
Supersedes row actions on iOS 11+
Keeps backwards compatibility on iOS < 11 by using the new action struct types and mapping into UITableViewRowAction objects as needed.
I've mapped the UISwipeActionsConfiguration and UIContextualAction types to our own struct types. This allowed me to vend UITableViewRowAction's in the iOS 9/10 case by creating them on demand. Otherwise, the appropriate swipe configuration objects are created (on demand) in the respective delegate methods. I dropped the one item from the handler closure (the context action itself) as I couldn't see a real use for this. You can't manipulate a context action within the closure (I tried) so it seems pointless to pass it through (and wouldn't work well for mapping to the iOS 9/10 case).
I've re-jigged the initializers a bit …
> Adds support for UITableView leading/trailing row actions

- FunctionalTableData/CellActions.swift
- FunctionalTableData/TableView/FunctionalTableData+UITableViewDelegate.swift
having the delegate for trailing results in row actions never being called on iOS 11+, so if they were intended to be used they would never be provided
This is a breaking change, however this is on master so I think we can start making breaking changes here in the move towards 2.0
> remove row actions entirely

- FunctionalTableData/TableView/FunctionalTableData+UITableViewDelegate.swift
Without this function the delete indicators show up when a table is in edit mode, even when we don't want them to. Adding this back allows them to be suppressed for now until a better solution is implemented
> reverting partial change and adding comment to explain what needs to happen

- FunctionalTableData/Separator.swift
- FunctionalTableDataTests/CellStyleTests.swift
We have a new design for separators that are inset on both sides (so they appear in the centre). This adds a new style to `Separator` called `bothInset` (naming suggestions very welcome!) that anchors the separator to the layout margins on both sides.
Technically adding a new enum value is a breaking change since it would require anyone that uses it in a switch statement without a `default` to add the new case, but I feel like most people aren't checking this enum in a switch statement outside of FTD.
> Add separator style inset on both sides

- FunctionalTableData/CellConfigType.swift
- FunctionalTableData/HostCell.swift
- FunctionalTableData/TableSectionChangeSet.swift
Moves the `type(of:)` comparisons into an overridable function that can be used in tests.
Captures the type of a cell in its `debugInfo()`
With this change I'm able to simulate different "types" of cells in test cases by having a custom type that conforms to CellConfigType and has the `isSameKind` function implemented. Additionally, capturing the type of a cell in a crash means that that data can be used in conjunction with the isSameKind
> Adds the isSameKind function

- FunctionalTableData/TableSectionChangeSet.swift
- when comparing the old/new types, compare against the proper old index path
- reloads require the before IndexPath, fixes to use that instead of the new IndexPath
> Fix invalid index paths on reload and an incorrect compare for updates

- FunctionalTableData.xcodeproj/project.pbxproj
- FunctionalTableData/TableView/FunctionalTableData+Cells.swift
- FunctionalTableData/TableView/FunctionalTableData+Data.swift
- FunctionalTableData/TableView/FunctionalTableData+UITableViewDataSource.swift
- FunctionalTableData/TableView/FunctionalTableData+UITableViewDelegate.swift
- FunctionalTableData/TableView/FunctionalTableData.swift
- FunctionalTableDataDemo/View Controllers/TableExampleController.swift
- FunctionalTableDataTests/FunctionalTableDataDelegateTests.swift
In the current implementation, when the user manually moves a row `tableView(_ tableView: UITableView, moveRowAt sourceIndexPath: IndexPath, to destinationIndexPath: IndexPath)` will modify the datasource `sections` but not the `sections` of `FunctionalTableData`. 
If the TableSection `didMoveRow` calls for a re-render then `FunctionalTableData` will detect changes. If the changes detected are "move" changes in an animated render, another unexpected move could be applied on top of the current one
> Move sections to a TableData class instead of duplicating the array

- FunctionalTableData.xcodeproj/project.pbxproj
- FunctionalTableData/CollectionView/FunctionalCollectionData+UICollectionViewDataSource.swift
- FunctionalTableData/CollectionView/FunctionalCollectionData+UICollectionViewDelegate.swift
- FunctionalTableData/CollectionView/FunctionalCollectionData.swift
- FunctionalTableData/TableData.swift
- FunctionalTableDataTests/FunctionalTableDataDelegateTests.swift
This one is just a code shuffle, making the new TableData type useable by FunctionalCollectionData as well (also did a `strongSelf` rename to just `self`)
> Making TableData a type used across both tables and collections

- FunctionalTableData/CellActions.swift
Makes using the API a bit simpler since it does the right thing by default but allows customization as needed
> Wraps the given previewingViewControllerAction in one that sets up the context

- FunctionalTableData/Separator.swift
- FunctionalTableDataTests/CellStyleTests.swift
This PR allows for more control over the separator in FunctionalTableData. This will be a breaking change for anyone using `.custom`. But it's safe for `.inset` and `.full`.
The demo project shouldn't visually change, and the tests have been modified to account for the new styling.
> Separator customization

- FunctionalTableData/TableView/FunctionalTableData+Cells.swift
- FunctionalTableData/TableView/FunctionalTableData+UITableViewDelegate.swift
- FunctionalTableDataDemo/View Controllers/TableExampleController.swift
When using CanSelectAction you should be able to cancel the selection and have the highlight cell revert to the previous one or none if nothing was selected. The code currently highlights the cell even if you cancel the selection. 
This PR saves the original highlight cell and sets it to be highlighted again if the selection is cancelled.
> Allow cells to be unhighlighted

- FunctionalTableData/TableView/FunctionalTableData+UITableViewDelegate.swift
When the SelectAction returns .deselect the delegate should be unhightlighting as well as deselecting.
> Remove highlight when selection action returns .deselect

- FunctionalTableData/CollectionView/FunctionalCollectionData.swift
- FunctionalTableData/TableView/FunctionalTableData.swift
Clearing the delegate isn't necessary and can cause a crash at dev time if the FTD or CTD gets deinitialized off of the main thread. So far I've only seen this happen while running unit tests, but it happens.
> Remove deinit

- FunctionalTableData.xcodeproj/project.pbxproj
- FunctionalTableData/TableSection.swift
- FunctionalTableDataTests/TableSectionTests.swift
Currently TableSection equality conformance only checks if the keys are equal. Although this specific equality function isn't used during FTD diffing, the fact this equality function is incomplete is causing sections to fail to update in some limited cases.
This PR implements proper equality of TableSections by checking all properties, including all rows.
> Add proper equality for TableSection

- Sources/FunctionalTableData/TableSection.swift
This changes makes sure that the index path is not empty when trying to access `.section`, which would result in a crash otherwise.
> Fix subscript crash

- Sources/FunctionalTableData/CollectionView/FunctionalCollectionData+UICollectionViewDelegate.swift
- Sources/FunctionalTableData/TableView/FunctionalTableData+UITableViewDelegate.swift
Allows for `canBeMoved` to also control if someone can take up this position. This is useful in situations were we want one of the items to be "unmovable" any any there trying to moved into its position
> CanBeMoved support in drag

- Sources/FunctionalTableData/CellActions.swift
- Sources/FunctionalTableData/CellConfigType.swift
- Sources/FunctionalTableData/HostCell.swift
This change allows the cell actions to be changed in place. They are still structs, so everything will still be copied around nicely.
I am working on a view controller that "auto magically" adds `visibilityAction` to all the cells it passes through its render, in order to do this I need to be able to modify the actions directly and set them back. Pretty much this
```swift
content.rows.enumerated().map { index, row in
var row = row
/// Store any previous visibility action to be called side by side with our new one.
let oldVisibilityAction = row.actions.visibilityAction
row.actions.visibilityAction = { [weak self] view, visible in
oldVisibilityAction?(view, visible)
guard visible else { return }
self?.didChangePage(to: index)
}
return row
}
```
> Mutable cell actions

- Sources/FunctionalTableData/TableSectionChangeSet.swift
Small fix that has been lurking around for a while. Thanks to Toussaint Stewart for catching this!
> Moved was using the wrong equatable

- FunctionalTableData.xcodeproj/project.pbxproj
- Sources/FunctionalTableData/Accessibility.swift
- Sources/FunctionalTableData/CellConfigType.swift
- Sources/FunctionalTableData/CollectionView/FunctionalCollectionData+UICollectionViewDataSource.swift
- Sources/FunctionalTableData/HostCell.swift
- Sources/FunctionalTableData/TableView/FunctionalTableData+UITableViewDataSource.swift
- Tests/FunctionalTableDataTests/AccessibilityTests.swift
- Tests/FunctionalTableDataTests/TableSectionChangeSetTests.swift
Starting point for a bit of extra accessibility data. The struct stores the iOS 13+ `userInputLabels` that are what the voice control system uses. This lets us put proper labels on cells so they can be tapped, instead of relying on the full accessibility string which can be quite cumbersome to speak.
> adding basic accessibility struct

- Sources/FunctionalTableData/CellActions.swift
- Sources/FunctionalTableData/TableView/FunctionalTableData+UITableViewDelegate.swift
[Apple docs](https://developer.apple.com/documentation/uikit/uitableviewdelegate/selecting_multiple_items_with_a_two-finger_pan_gesture)
---- 
This adds support for multi item selection in an FTD tableview. When the `tableView.allowsMultipleSelectionDuringEditing` is set to true, list multi selection can be initiated with a two finger swipe along the rows, or, if editing mode is already enabled, single finger swipe down the rows.
Lifecycle of this interaction is along the lines of:
- **`tableView(_:shouldBeginMultipleSelectionInteractionAt:) -> Bool`**: Determines if these gestures are available.
- **`tableView(_:didBeginMultipleSelectionInteractionAt:)`**: Called when a multi item selection gesture has begun. 
- Handler forwarded to `CellActions` via `beginMultiSelectAction`
- …
> Support multi item selection via gestures

- Sources/FunctionalTableData/CellActions.swift
- Sources/FunctionalTableData/CellStyle.swift
- Sources/FunctionalTableData/CollectionView/FunctionalCollectionData+UICollectionViewDataSource.swift
- Sources/FunctionalTableData/CollectionView/FunctionalCollectionData.swift
- Sources/FunctionalTableData/TableView/FunctionalTableData+Cells.swift
- Sources/FunctionalTableData/TableView/FunctionalTableData+UITableViewDataSource.swift
- Sources/FunctionalTableData/TableView/FunctionalTableData+UITableViewDelegate.swift
- Tests/FunctionalTableDataTests/CellStyleTests.swift
`UITableViewCell` has a selected property, which is automatically toggled through the UITableView in many cases. For example, if a user taps on a cell it is first highlighted then selected. If a user swipes on a cell, then the table view determines that that cell is now selected and shows the leading or trailing swipe actions accordingly.
If the table view supports multi-selection, then the table view shows checkboxes as a left accessory view of the cell, and if a cell is selected (via either a double-finger swipe gesture or a single tap), then its index path is added to `indexPathsForSelectedRows` automatically. 
If, however, the tableView is reloaded, or simply displaying for the first time and we want certain cells pre-selected, then `indexPathsForSelectedRows` is reset to nil. …
> Added cell selection state to cell actions.

- Sources/FunctionalTableData/TableView/FunctionalTableData+UITableViewDelegate.swift
Because of our custom selection logic for `UITableView`, cells that are selected are usually also highlighted using `CellStyler`.
The problem comes when gestures are used for multi-selection, or accessory view are tapped when in multi-selection, the last selected cell is always set as the highlighted cell. When using gestures or tapping the accessory view, the normal flow of `shouldHighlightCellAt` is not called, meaning that the cell does not properly un-highlight.
This PR simply adds logic to say: when a cell is de-selected, if it is still highlighted, unhighlight it.
In almost all cases except multi-select, this would have no effect because the cell is highlighted and un-highlighted before it is selected or de-selected.
> Unhighlight cell on deselection.

- Sources/FunctionalTableData/CellStyle.swift
- Tests/FunctionalTableDataTests/CellStyleTests.swift
The `CellStyle` already takes in a `BackgroundViewProvider` for the `backgroundView` property, but we can easily extend this idea to also take in a `BackgroundViewProvider` for the `selectedBackgroundView` property as well. 
This will allow for custom views on selection of cells.
> Adds support for a selectionBackgroundProvider in the cellStyle.

- Sources/FunctionalTableData/TableView/FunctionalTableData+UITableViewDelegate.swift
In order for `tableView(_:, didBeginMultipleSelectionInteractionAt:)` to be called, editing mode needs to be enabled on the tableView. This removes that redundant, and potentially costly (in terms of performance), call to setting and animating the tableView to editing mode.
> Remove redundant call to tableView.setEditing(_:animated:)

- FunctionalTableData.xcodeproj/project.pbxproj
- Sources/FunctionalTableData/CellConfigType.swift
- Sources/FunctionalTableData/CellStyle.swift
- Sources/FunctionalTableData/Separator.swift
- Sources/FunctionalTableData/TableSection.swift
- Sources/FunctionalTableData/TableSectionHeaderFooter.swift
- Sources/FunctionalTableData/TableView/FunctionalTableData+Classic.swift
- Sources/FunctionalTableData/TableView/FunctionalTableData+DiffableDataSource.swift
- Sources/FunctionalTableData/TableView/FunctionalTableData+UITableViewDataSource.swift
- Sources/FunctionalTableData/TableView/FunctionalTableData.swift
- Sources/FunctionalTableData/TableView/TableItemConfigType.swift
- Tests/FunctionalTableDataTests/DiffableDataSourceFunctionalDataTests.swift
- Tests/FunctionalTableDataTests/DiffableDataSourceFunctionalTableDataPerformanceTests.swift
- Tests/FunctionalTableDataTests/DiffableDataSourceTableCellReuseTests.swift
- Tests/FunctionalTableDataTests/TableSectionChangeSetTests.swift
- Tests/FunctionalTableDataTests/TableSectionTests.swift
To workaround crashes in UITableView with large change sets, use UITableViewDiffableDataSource when available (iOS 13 or greater)
Created an Impl protocol, with two implementations:
1. Original Functional Table Data algorithm
2. UITableViewDiffableDataSource-backed implementation for iOS 13 and up.
Then just followed the consequences of that. Any other changes are due to getting it working on IOS 13 at runtime. Tests with data exhibiting the crash with the original table data algorithm pass with diffable data sources.
> Use NSDiffableDataSource for iOS 13 or greater

- Sources/FunctionalTableData/TableView/FunctionalTableData+DiffableDataSource.swift
Fixes little bug introduced in the last commit.
Boolean value was incorrect, so it would animate on the first pass; we want the opposite.
> Fix boolean logic to not animate on first load of data
